rvcal/shifts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('shifts.views',
  (r'index/', 'index'), 
  (r'events/', 'events'), 
  (r'login/', 'user_login'), 
  (r'logout/', 'user_logout'), 
)

rvcal/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from rvcal import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^rvcal/', include('rvcal.shifts.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:], 'serve',
         {'document_root':settings.STATIC_ROOT, 'show_indexes':True}),
            
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'serve',
         {'document_root':settings.MEDIA_ROOT, 'show_indexes':True}),
        )

rvcal/shifts/models.py
from django.db import models
from django.contrib.auth.models import User

class Shift(models.Model):
  person = models.ForeignKey(User, related_name="shift_user")
  comment = models.CharField(max_length=255, blank=True)
  date = models.DateField('Shift date')

  def __unicode__(self):
    return self.person.username + " - " + self.date.isoformat()

rvcal/shifts/forms.py
# -*- coding: utf-8 -*- 

from django import forms
from django.contrib.auth.models import User

class ShiftForm(forms.Form):
  person = forms.ModelChoiceField(queryset=User.objects.all(), 
                                 label='Haker(ica)', 
                                 empty_label=None)
  date = forms.CharField(label='Datum',
                         widget=forms.TextInput(attrs={ 'readonly': 'readonly' }))
  clear = forms.BooleanField(label='Obriši do sada unesena dežurstva za ovaj dan', required=False)

class LoginForm(forms.Form):
  username = forms.CharField(label='Username', widget=forms.TextInput(attrs={}))
  password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={}))

rvcal/shifts/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.utils import simplejson
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from forms import ShiftForm, LoginForm
from models import Shift
from datetime import datetime

# user login
def user_login(request):
  context = {}
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    form = LoginForm(request.POST)
    user = authenticate(username=username, password=password)
    if user is not None and user.is_active and form.is_valid():
      login(request, user)
      return HttpResponseRedirect(reverse(index))
    else:
      return HttpResponseRedirect(reverse(user_login))
  else:
    template = 'login.html'
    form = LoginForm()
    context['form'] = form
    return render_to_response(template, context)

def user_logout(request):
  logout(request)
  return HttpResponseRedirect(reverse(user_login))

# serves main page with calendar
def index(request):
  if not request.user.is_authenticated():
    return HttpResponseRedirect(reverse(user_login))

  context = {}
  if request.method == 'POST':
    form = ShiftForm(request.POST)
    context['form'] = form
    if form.is_valid():
      if form.cleaned_data['clear']:
        Shift.objects.filter(date=datetime.strptime(form.cleaned_data['date'],
                             "%Y-%m-%d")).delete()

      shift = Shift(
        person=form.cleaned_data['person'],
        date=datetime.strptime(form.cleaned_data['date'], "%Y-%m-%d"))
      shift.save()
      return HttpResponseRedirect(
        reverse(index))
  else:
    form = ShiftForm(initial={ "person": request.user.id })
    context['form'] = form

  template = 'index.html'
  return render_to_response(template, context_instance=RequestContext(request, context))

# returns list of events for calendar
def events(request):
  events = []
  shifts = Shift.objects.all()
  for shift in shifts:
    events.append(
      { 'title': shift.person.username,
        'start': shift.date,
      })
  return HttpResponse(
    simplejson.dumps(events, cls=DjangoJSONEncoder),
    mimetype="text/plain")

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{%block meta_description%}{%endblock%}" />
    <meta name="keywords" content="{%block meta_keywords%}{%endblock%}" />
    <link rel="stylesheet" href="/static/css/blueprint/screen.css" type="text/css" media="screen, projection" />
    <link rel="stylesheet" href="/static/css/blueprint/print.css" type="text/css" media="print" />
    <link rel="stylesheet" href="/static/css/rvcal.css" type="text/css" media="screen, projection" />
    <!--[if lt IE 8]><link rel="stylesheet" href="/static/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <link rel="icon" type="image/x-icon" href="/static/images/favico.png" />
    <script type="text/javascript" src="/static/js/jquery/jquery-1.4.4.min.js"></script>
    {% block extra_head %}{% endblock %}
  </head>
  {% block body %}
  <body>
    <div class="container">
      <div class="header span-24 last">
        {% block header %}{% endblock %}
        {% if user.is_authenticated %}<a href="{% url shifts.views.user_logout %}">logout ({{ user.username }})</a>{% endif %}
      </div>
      <div class="main span-24 last">
        {% block main %}{% endblock %}
      </div>
      <div class="footer span-24 last">
        {% block footer %}{% endblock %}
      </div>
    </div>
    {% block extra_scripts %}
    <script type="text/javascript" src="/static/js/fullcalendar/fullcalendar.min.js"></script>
    <script type="text/javascript" src="/static/js/rvcal.js"></script>
    {% endblock %}
  </body>
  {% endblock %}
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Dežurstva u mami{% endblock %}
{% block meta_description %}{{description_tag}}{% endblock %}
{% block meta_keywords %}{{keywords_tag}}{% endblock %}

{% block header %}
<div class="span-2">
  <a href="{% url shifts.views.index %}">
    <img src="/static/images/rv_logo.png"></img>
  </a>
</div>
<div class="span-22 last">
  <h1>
    <a href="{% url shifts.views.index %}">
      <span class="boxed">Razmjena vještina/Hacklab u mami dežurstva</span>
    </a>
  </h1>
</div>
{% endblock %}

{% block main %}
<div id="entryform">
  <form method="post" action="{% url shifts.views.index %}">
    {% if form.errors %}
    <div class="error">{{form.errors}}</div>
    {% endif %}
    Haker(ica) {{ form.person }} dežura dana {{ form.date }}?<br />
    {{ form.clear }} <label for="id_clear">{{ form.clear.label }}</label><br />
    <input type="submit" value="Potvrdi" name="submit" id="submit" />
  </form>
</div>

<div id="calendar"></div>
{% endblock %}

{% block footer %}
<span class="boxed">
Razmjena vještina - 
<a href="http://razmjenavjestina.org/">razmjenavjestina.org</a> -
<a href="https://github.com/nikolaplejic/rvcal/">github.com/nikolaplejic/rvcal</a>
</span>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Dežurstva u mami{% endblock %}
{% block meta_description %}{{description_tag}}{% endblock %}
{% block meta_keywords %}{{keywords_tag}}{% endblock %}

{% block header %}
<div class="span-2">
  <a href="{% url shifts.views.index %}">
    <img src="/static/images/rv_logo.png"></img>
  </a>
</div>
<div class="span-22 last">
  <h1>
    <a href="{% url shifts.views.index %}">
      <span class="boxed">Razmjena vještina/Hacklab u mami dežurstva</span>
    </a>
  </h1>
</div>
{% endblock %}

{% block main %}
<div id="loginform" style="width: 430px; margin: 0 auto;">
  <form method="post" action="{% url shifts.views.user_login %}">
    <label for="username">Username:</label> <input type="text" name="username" id="username" size="30" />@bljak.org<br />
    <label for="password">Password:</label> <input type="password" name="password" id="password" size="30" /><br />
    <input type="submit" value="submit" id="submit" />
  </form>
</div>
{% endblock %}

{% block footer %}
<span class="boxed">
Razmjena vještina - 
<a href="http://razmjenavjestina.org/">razmjenavjestina.org</a> -
<a href="https://github.com/nikolaplejic/rvcal/">github.com/nikolaplejic/rvcal</a>
</span>
{% endblock %}